### PR TITLE
Unity Fullscreen Feature

### PR DESCRIPTION
**Pull request by eitanalka**
Functionality is just like UnityEvent except you create a UnityFullscreen function that sets the screen to fullscreen when emit is called.

### CODE REVIEW

**Comment by jeffreylanters** [comment]
Can you please include the source.

**Comment by eitanalka** [comment]
Just added it

**Comment by jeffreylanters** [comment]
Thanks, can you please merge into development.

**Comment by eitanalka** [comment]
Just did

**Pull request merged**
